import { Roboto } from "next/font/google";
import "./globals.css";
import Header from "./components/header/Header";

const roboto = Roboto({ 
  weight: '400',
  subsets: ["latin"],
  display: 'swap'
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={roboto.className}>
      <body className="bg-slate-900">
        <Header />
        {children}
      </body>
    </html>
  );
}
